### ISSUE TITLE
Format is different than STON

### ISSUE THREAD

**Issue by seandenigris** [JupiterJones/amber-ston#2]
For example, in STON proper `STON toString: (MyObject new rating: 5; yourself)` -> `'MyObject{#rating:5}'`, but in amber-ston the same expression gives `'MyObject{'rating':5,'location':nil}'`.

I noticed two differences:
- `'instVarName'` instead of `#instVarName`
- it pads the data with unnecessary nil variables (created Issue #3)

**Comment by JupiterJones** [comment]
Yes both those issues will be resolved for custom object serialisation.

Outside of the specific case of instVars, Symbols will still be an issue and `STON toString: #name -> 'name'` will up as `'name':'name'`
ie. Symbols will materialise to Strings, and nothing (apart from instVars) will serialise as Symbols.
