### ISSUE TITLE
Don't serialize nil instVars

### ISSUE THREAD

**Issue by seandenigris** [JupiterJones/amber-ston#3]

**Comment by JupiterJones** [comment]
Complete

**Comment by seandenigris** [comment]
You're too fast! I was just committing :) Quick question, when would one want #stonShouldWriteNilInstVars? What is the use case?

**Comment by JupiterJones** [comment]
Not sure. It's one of the tests in the other implementations so I'm supporting it here as well :) Not a good answer, I know.

**Comment by seandenigris** [comment]
Good enough for me :) Are you writing from scratch, or did you start with another implementation?

**Comment by JupiterJones** [comment]
I started with the Pharo implementation and attempting to get as many tests passing as possible. It won't be possible to get everything working (mainly because of Symbols, Characters, and a few other classes that aren't present in Amber, but It should be good enough to support most use cases.

**Comment by seandenigris** [comment]
Cool :)
